import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Inter } from "next/font/google";
import { Providers } from "./providers";
import SideNav from "../components/Menu/Side-nav";
import MarginWidthWrapper from "../components/Menu/margin-width-wrapper";
import Header from "../components/Menu/Header";
import HeaderMobile from "../components/Menu/HeaderMobile";
import PageWrapper from "../components/Menu/page-wrapper";

import { AuthProvider } from "@/app/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <AuthProvider> {/* Mover AuthProvider aquí */}
            <div className="flex">
              <SideNav />
              <main className="flex-1">
                <MarginWidthWrapper>
                  <Header />
                  <HeaderMobile />
                  <PageWrapper>
                    {children}
                  </PageWrapper>
                </MarginWidthWrapper>
              </main>
            </div>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
